---
title: "Melanoma"
author: "MatteoAndriolo"
output: 
  html_document: 
    toc: true
    toc_depth: 3
    number_sections: true
---

```{r, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, warning = FALSE, message = TRUE)
```

```{r setup}
# Placed inside Rprofile
source("../src/R/imports.R")
source("../src/R/classes.R")
library(Seurat)
library(ggplot2)
library(here)
library(archetypes)
library(tidyr)
library(dplyr)
if (!require(kneedle)) {
  install.packages("quantmod")
}
devtools::install_github("etam4260/kneedle")
library(kneedle)
library(cowplot)

HVF <- TRUE
TEST <- TRUE 
TEST <- FALSE

TEST_genes <- 300
TEST_samples <- 500

out_path <- "../out/Melanoma"
```

# Load Dataset
```{r Load Melanoma dataset}
melanoma=new("Melanoma")
melanoma = obj_loadData(melanoma, test=TRUE);
```
# Visualize data

```{r}
obj_visualizeData(melanoma, out_path)
```


# Archetypes
```{r AA, message=TRUE, warning=TRUE}

melanoma=obj_performArchetypes(melanoma)

#save(a, file = sprintf("%s/Archetypes_%2d.rds", out_path, k))
```

## Visualize Archetypes
```{r Visualize AA, message=TRUE, warning=TRUE}
obj_visualizeArchetypes(melanoma, out_path)
```

```{r}
simplexplot(melanoma@a)
```


## Plot Umap Archetypes

```{r}
obj_umapArchetypes(melanoma,out_path)
```


# Seurat
```{r}
DimPlot(melanoma@se, reduction = "umap")
#DimPlot(melanoma@se, reduction = "umap", group.by = "cell_type")
```

```{r}
se <- FindNeighbors(melanoma@se, dims = 6:15)
se <- FindClusters(melanoma@se, resolution = 0.5)
```
