---
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
source("/app/Rmd/imports.R")
```

```{r}
data_path <- "/app/data/Melanoma/GSE72056_melanoma_single_cell_revised_v2.txt"
se <- read.table(data_path, header = TRUE)

# Remove duplicated genes
se <- se[!duplicated(se[, 1]), ]

# Setup dimnames and metadata
rownames(se) <- se[, 1]
se <- se[, 2:ncol(se)]
metadata <- se[1:3, ]
metadata <- t(metadata) %>%
  data.frame() %>%
  mutate(across(where(is.character), as.numeric))

se <- se[4:nrow(se), ]
se <- se %>%
  data.frame() %>%
  mutate(across(where(is.character), as.numeric))

message("Original dimensions ", dim(se)[[1]], " ", dim(se)[[2]])
```

```{r}
# Remove row and columns with all zeroes
se <- se[Matrix::rowSums(se) > 0, Matrix::colSums(se) > 0]
message("After removing all zero rows and columns ", dim(se)[[1]], " ", dim(se)[[2]])
```

```{r}
obj@se <- CreateSeuratObject(se)
```

```{r}
obj@params$pathw <- pathways[[1]]
obj <- obj_setGenes(obj)
message(obj@params$pathw, " - ", length(obj@params$genes))
gene_names <- rownames(obj@se)
gene.flag <- gene_names %in% obj@params$genes
m <- obj@se[obj@params$genes, ]
message("Dimension filtered genes ", dim(m)[[1]], " ", dim(m)[[2]])
m <- m@assays$RNA@layers$counts
m <- m[Matrix::rowSums(m) > 0, Matrix::colSums(m) > 0]
message("After removing all zero rows and columns ", dim(m)[[1]], " ", dim(m)[[2]])
```

```{r}
obj@params$pathw <- pathways[[2]]
obj <- obj_setGenes(obj)
message(obj@params$pathw, " - ", length(obj@params$genes))
gene_names <- rownames(obj@se)
gene.flag <- gene_names %in% obj@params$genes
m <- obj@se[obj@params$genes, ]
message("Dimension filtered genes ", dim(m)[[1]], " ", dim(m)[[2]])
m <- m@assays$RNA@layers$counts
m <- m[Matrix::rowSums(m) > 0, Matrix::colSums(m) > 0]
message("After removing all zero rows and columns ", dim(m)[[1]], " ", dim(m)[[2]])
```
