---
title: "obj"
author: "MatteoAndriolo"
output: 
  html_document: 
    toc: true
    toc_depth: 3
    number_sections: true
params:
  TEST: FALSE
  HVF: TRUE
  TEST_genes: 300
  TEST_samples: 500
  CLASS.NAME: NULL
  pathw: NULL
  out_path: NULL
---

```{r, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, warning = FALSE, message = TRUE)
```


```{r setup, message=FALSE, warning=FALSE}
source("imports.R")
source("classes.R")

# TEST <- params$TEST
# HVF <- params$HVF
# TEST_genes <- params$TEST_genes
# TEST_samples <- params$TEST_samples
# CLASS.NAME <- params$CLASS.NAME
# if (is.null(CLASS.NAME)) {
#  stop("CLASS.NAME is NULL")
# }
# pathw <- params$pathw
# out_path <- params$out_path

##TODO  Remove this part
#TEST <- TRUE
#HVF <- FALSE
#TEST_genes <- 300
#TEST_samples <- 500
#CLASS.NAME <- "Exp1"
#pathw <- "MAPK signaling pathway"
#out_path <- sprintf("/app/out/%s/%s_files", CLASS.NAME, CLASS.NAME)
```

# Load Dataset, hide all outputs
```{r Load obj dataset, message=FALSE, warning=FALSE}
obj <- new(CLASS.NAME)
obj <- obj_loadData(obj, test = TEST, pathw = pathw, test_genes = TEST_genes, test_samples = TEST_samples)
```

```{r Visualize obj dataset, message=FALSE, warning=FALSE, tabbed=TRUE}
obj <- obj_visualizeData(obj, out_path)
```


# Archetypes
```{r AA, message=TRUE, warning=TRUE}
obj <- obj_performArchetypes(obj)
```

## Visualize Archetypes
```{r Visualize AA, message=FALSE, warning=TRUE, paged.print=FALSE}
obj <- obj_visualizeArchetypes(obj, out_path)
```

```{r Visualize AA simplex, message=FALSE, warning=TRUE}
simplexplot(obj@a)
```


## Plot Umap Archetypes

```{r Visualize Umap AA, message=FALSE, warning=TRUE}
obj <- obj_umapArchetypes(obj, out_path)
```


## Seurat
#```{r}
#DimPlot(obj@se, reduction = "umap")
## DimPlot(obj@se, reduction = "umap", group.by = "cell_type")
#```
#
#```{r}
#se <- FindNeighbors(obj@se, dims = 6:15)
#se <- FindClusters(obj@se, resolution = 0.5)
#```
