---
title: "Melanoma"
author: "MatteoAndriolo"
output: 
  html_document: 
    toc: true
    toc_depth: 3
    number_sections: true
---

```{r setup, include=FALSE}
# Load necessary libraries and set global options
knitr::opts_chunk$set(echo = TRUE, warning = FALSE, message = FALSE)

# libraries
library(Seurat)
library(ggplot2)
library(here)
library(archetypes)
library(tidyr)
library(dplyr)

# Setup all paths
data_path="../data/Melanoma/GSE72056_melanoma_single_cell_revised_v2.txt"
out_path="../out/Melanoma"

# Setup testing phase
#TEST=TRUE
TEST=FALSE
TEST_ngenes=300
TEST_nsamples=500

# Archetypes
k= 15
```

# Load Dataset
```{r Load Melanoma dataset, message=TRUE, warning=TRUE, paged.print=FALSE}
ge <- read.table(data_path, header = TRUE)
ge=ge[!duplicated(ge[,1]),] # remove duplicated genes
rownames(ge)=ge[,1]         # extract from matrix rownames
ge=ge[,2:ncol(ge)]          # elide rownames from gene expression matrix

metadata=ge[1:3,]          # extract metadata
metadata <- t(metadata) %>%
    data.frame() %>% 
    mutate(across(where(is.character), as.numeric)) 

ge=ge[4:nrow(ge),]
ge <- ge %>% 
    data.frame() %>% 
    mutate(across(where(is.character), as.numeric)) 
# -------- END BASIC SETUP
if(TEST){
    tgenes=min(TEST_ngenes, nrow(ge))
    tsamples=min(TEST_nsamples, ncol(ge))
    metadata=metadata[1:tsamples,]
    ge=ge[1:tgenes,1:tsamples]
    rm(tgenes,tsamples)
}

# -------- SEURAT
se <- CreateSeuratObject(ge,project="MelanomaSC",meta.data=metadata)
# Skip normalization since data is already normalized
se <- ScaleData(se, layer= "counts") 
se <- FindVariableFeatures(se, hvf.nfeatures = hvf.nfeatures)

se = RunPCA(se, features = VariableFeatures(se))
se = RunUMAP(se, features = VariableFeatures(se))
```

# Visualize data
```{r Elbowplot and Visualization, message=TRUE, warning=TRUE, paged.print=FALSE}
imgname=sprintf("%s/PCA.png", out_path)
message(sprintf("Saving Imagine --- %s",imgname))
pcaplot=PCAPlot(se)
# ggsave(imgname, plot=pcaplot)
pcaplot
```

```{r UMAP, message=TRUE, warning=TRUE, paged.print=TRUE}
imgname=sprintf("%s/UMAP.png", out_path)
message(sprintf("Saving Imagine --- %s",imgname))
umapplot = UMAPPlot(se)
# ggsave(imgname, plot=umapplot)
umapplot
```

```{r Elbowplot, message=TRUE, paged.print=TRUE}
imgname=sprintf("%s/elbow.pdf", out_path)
message(sprintf("Saving Imagine --- %s",imgname))
elbowplot=ElbowPlot(se)
# ggsave(imgname, plot=elbowplot)
elbowplot
```

# Archetypes
```{r AA, message=TRUE, warning=TRUE, paged.print=TRUE}
if(TEST){
    m = se@assays$RNA@layers$counts[which(se@assays$RNA@meta.data$vf_vst_counts_rank>0),]
}else{
    m = se@assays$RNA@layers$counts
}
m=as.matrix(m)

s=timestamp()
a=archetypes::archetypes(m, k=k, verbose=TRUE, maxIterations=10)
e=timestamp()

save(a,file=sprintf("%s/Archetypes_%2d.rds",out_path,k))
```

## Visualize Archetypes
```{r Visualize AA, message=TRUE, warning=TRUE, paged.print=TRUE}
imgname=sprintf("%s/Archetypes_%2d.png", out_path,k)
plotarchetyps = xyplot(a,m)
# ggsave(imgname, plot=plotarchetyps)
plotarchetyps
```