# FROM rocker/cuda
FROM rocker/rstudio

COPY .Rprofile /home/rstudio/.Rprofile
COPY containers/installation.sh /app/installation.sh

ARG DEBIAN_FRONTEND=noninteractive

RUN "apt update;\
    apt upgrade;"

RUN /app/installation.sh
