FROM rocker/rstudio

COPY .Rprofile /home/rstudio/.Rprofile

ARG DEBIAN_FRONTEND=noninteractive

RUN apt update; \
    apt upgrade; \
    apt install -y libhdf5-dev libglpk-dev

# Install R packages
#RUN R -e 'usethis::gitcreds_set(url = "https://github.com")'

RUN R -e "update.packages(ask = FALSE, checkBuilt = TRUE)"
RUN R -e "install.packages(c('usethis','rhdf5','remotes','devtools','BiocManager','units','sf','spdep'))"
RUN R -e "BiocManager::install(c('BiocGenerics', 'DelayedArray', 'DelayedMatrixStats', 'limma', 'lme4', 'S4Vectors', 'SingleCellExperiment', 'SummarizedExperiment', 'batchelor', 'HDF5Array', 'terra', 'ggrastr'))"

RUN R -e "install.packages('archetypes')"

# Install Seurat 
RUN R -e 'remotes::install_github("satijalab/seurat", "seurat5", quiet = TRUE);'
RUN R -e 'remotes::install_github("satijalab/seurat-data", "seurat5", quiet = TRUE);'
RUN R -e 'remotes::install_github("satijalab/seurat-wrappers", "seurat5", quiet = TRUE);'
RUN R -e 'remotes::install_github("bnprks/BPCells", quiet = TRUE);'
# RUN R -e 'remotes::install_github("satijalab/azimuth", "seurat5", quiet = TRUE);'
# RUN R -e 'remotes::install_github("stuart-lab/signac", "seurat5", quiet = TRUE);'
# RUN R -e 'setRepositories(ind=1:3) ; install.packages("Signac") '

# Install monocle3
RUN R -e "devtools::install_github('cole-trapnell-lab/monocle3')"
