FROM rocker/rstudio

COPY .Rprofile /home/rstudio/.Rprofile

ARG DEBIAN_FRONTEND=noninteractive

RUN apt update; \
    apt upgrade; \
    apt install -y libhdf5-dev libglpk-dev pandoc git build-essential tcl tk

# Install R packages
#RUN R -e 'usethis::gitcreds_set(url = "https://github.com")'
ARG GITHUB_PAT
RUN  git config --global credential.helper \
    '!f() { echo username=author; echo "password=$GITHUB_PAT"; };f'

RUN R -e "update.packages(ask = FALSE, checkBuilt = TRUE)"
RUN R -e "install.packages(c('usethis','rhdf5','remotes','devtools','BiocManager','units','sf','spdep', 'archetypes','quantmod'), Ncpus = parallel::detectCores(), make.args = c('-j', parallel::detectCores()))"
RUN R -e "BiocManager::install(c('BiocGenerics', 'DelayedArray', 'DelayedMatrixStats', 'limma', 'lme4', 'S4Vectors', 'SingleCellExperiment', 'SummarizedExperiment', 'batchelor', 'HDF5Array', 'terra', 'ggrastr','glmGamPoi'), Ncpus = parallel::detectCores(), make.args = c('-j', parallel::detectCores()))"

# packages required by Seurat
# 'glmGamPoi' for faster SCtransform (seurat sc normalization QC and hvg selection)

# Install Seurat 
RUN R -e 'install.packages("dplyr")'
RUN R -e 'remotes::install_github("satijalab/seurat", "seurat5", quiet = TRUE);'
RUN R -e 'remotes::install_github("satijalab/seurat-data", "seurat5", quiet = TRUE);'
RUN R -e 'remotes::install_github("satijalab/seurat-wrappers", "seurat5", quiet = TRUE);'
RUN R -e 'remotes::install_github("bnprks/BPCells", quiet = TRUE);'
# RUN R -e 'remotes::install_github("satijalab/azimuth", "seurat5", quiet = TRUE);'
# RUN R -e 'remotes::install_github("stuart-lab/signac", "seurat5", quiet = TRUE);'
# RUN R -e 'setRepositories(ind=1:3) ; install.packages("Signac") '

# Install monocle3
#RUN R -e "devtools::install_github('cole-trapnell-lab/monocle3')"

RUN R -e 'devtools::install_github("etam4260/kneedle")'